# Generated by Django 5.0.2 on 2024-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetogetheruser',
            name='avatar_url',
            field=models.CharField(default='https://res.cloudinary.com/dxgl4eyhq/image/upload/v1701036989/huddled/images/defaults/profile_ioi9ke.jpg', max_length=150),
        ),
        migrations.AddField(
            model_name='codetogetheruser',
            name='bio',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codetogetheruser',
            name='blog_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codetogetheruser',
            name='location',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
    ]
