# Generated by Django 5.0.2 on 2024-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_subscriptiontype_submission_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptiontype",
            old_name="price",
            new_name="monthly_price",
        ),
        migrations.AddField(
            model_name="subscriptiontype",
            name="yearly_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
